package com.zagros.personalnotes.core;

import android.content.Context;

/**
 * A Presenter acts as a controller for both the {@link UpdatableView} (typically a fragment) and
 * the {@link Model} for the MVP architectural pattern.
 * <p/>
 * The Presenter listens to events generated by the {@link UpdatableView}, and passes them on to
 * the {@link Model}, which modifies its data as required. The Presenter also listens to events
 * generated by the {@link Model} and then asks the {@link UpdatableView} to update itself.
 */
public interface Presenter {


    /**
     * Sets the {@code model} this Presenter controls.
     */
    void setModel(Model model);

    /**
     * Sets the {@code view} this Presenter controls.
     */
    void setUpdatableView(UpdatableView view);


    /**
     * Sets the {@code queries} to load when the {@link android.app.Activity} using this Presenter
     * is created.
     */
    void setInitialQueriesToLoad(QueryEnum[] queries);

    /**
     * Sets the user {@code actions} allowed by this Presenter.
     */
    void setValidUserActions(UserActionEnum[] actions);

    /**
     * Cleans up all references to objects containing an {@link android.view.View} or
     * {@link android.content.Context} in order to help with garbage collection and
     * avoid memory leaks.
     */
    void cleanUp();

    /**
     * @return the {@link android.content.Context} to which this Presenter is attached.
     */
    Context getContext();
}